L4/lesson4/urls.py
from . import views
from django.urls import path


app_name = 'lesson4'

urlpatterns = [
    path('', views.get_context_data, name='index'),
    path('insert/', views.insert_form, name='insert'),
]

L4/lesson4/views.py
from django.shortcuts import render, redirect
from . import models, forms


def get_context_data(request):
    form = forms.ProductsForm()
    model = models.Products
    context = {'table': model.objects.all(),
               'product_name': form.fields['name'].label,
               'product_date': form.fields['date_rec'].label,
               'product_price': form.fields['price'].label,
               'product_u_measure': form.fields['u_measure'].label,
               'product_provider': form.fields['name_provider'].label,
               }
    return render(request, 'goods_list.html', context=context)


def insert_form(request):
    form = forms.ProductsForm()
    print(form)
    if request.method == 'POST':
        form = forms.ProductsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = forms.ProductsForm()
    return render(request, 'good_create.html', {'form': form})

L4/lesson4/templates/good_create.html
{% extends 'form.html' %}
{% load bootstrap %}
{% block content %}
<h1>Добавление товаров</h1><br>
<form class="products-form" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form | bootstrap }}
    <button type="submit" class="btn btn-success">Сохранить</button>
</form>
{% endblock %}

L4/lesson4/templates/goods_list.html
{% extends 'base.html' %}
{% block content %}
    <h1>Таблица товаров</h1><br>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>{{ product_name }}</th>
                <th>{{ product_date }}</th>
                <th>{{ product_price }}</th>
                <th>{{ product_u_measure }}</th>
                <th>{{ product_provider }}</th>
            </tr>
        </thead>
        <tbody>
        {% for i in table %}
            <tr>
                <td>{{ i.name }}</td>
                <td>{{ i.date_rec }}</td>
                <td>{{ i.price }}</td>
                <td>{{ i.u_measure }}</td>
                <td>{{ i.name_provider }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
<form method="GET" action="{% url 'lesson4:insert' %}">
    <button type="submit" class="btn btn-success">Добавить строку</button>
</form>
{% endblock %}

L4/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Урок 4</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
<div class="container">
       {% block content %}
       {% endblock %}
   </div>
</body>
</html>

L4/templates/form.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Добавить строку</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
<div class="container">
{% block content %}
{% endblock %}
</div>>
</body>
</html>