L5/DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from lesson4 import views

urlpatterns = [
    path('', include('lesson4.urls')),
    # path('', views.MainView.as_view(), name='index'),
    path('admin/', admin.site.urls),
]

L5/lesson4/urls.py
from . import views
from django.urls import path


app_name = 'lesson4'

urlpatterns = [
    path('', views.get_context_data, name='index'),
    path('insert/', views.insert_form, name='good_create'),
]

L5/lesson4/models.py
from django.db import models


class Products(models.Model):
    name = models.CharField(verbose_name=u'Наименование товара',
                            max_length=255)
    date_rec = models.DateField(verbose_name=u'Дата поступления')
    price = models.PositiveIntegerField(verbose_name=u'Цена', default=0)
    u_measure = models.CharField(verbose_name=u'Единица измерения',
                                 max_length=30)
    name_provider = models.CharField(verbose_name=u'Поставщик',
                                     max_length=255)

    def __unicode__(self):
        return self.name

L5/lesson4/forms.py
from django.forms import ModelForm
from .models import Products


class ProductsForm(ModelForm):
    class Meta:
        model = Products
        fields = ['name', 'date_rec', 'price', 'u_measure', 'name_provider']

L5/lesson4/views.py
from django.shortcuts import render
from . import models, forms
from django.template.loader import render_to_string
from django.http import JsonResponse


def get_context_data(request):
    form = forms.ProductsForm()
    model = models.Products
    context = {'table': model.objects.all(),
               'product_name': form.fields['name'].label,
               'product_date': form.fields['date_rec'].label,
               'product_price': form.fields['price'].label,
               'product_u_measure': form.fields['u_measure'].label,
               'product_provider': form.fields['name_provider'].label,
               }
    return render(request, 'goods_list.html', context=context)


def insert_form(request):
    if request.method == 'POST':
        form = forms.ProductsForm(request.POST)
    else:
        form = forms.ProductsForm()
    return save_good_form(request, form, 'good_create.html')


def save_good_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            goods = models.Products.objects.all()
            data['html_good_list'] = render_to_string('goods_list.html', {
                'goods': goods
            })
        else:
            data['form_is_valid'] = False
            context = {'form': form}
            data['html_form'] = render_to_string(template_name, context, request=request)
    else:
        data['form_is_valid'] = False
        context = {'form': form}
        data['html_form'] = render_to_string(template_name, context, request=request)
        print(data)

    return JsonResponse(data)

L5/lesson4/templates/good_create.html
{% extends 'base.html' %}
{% block content %}
<h1>Добавление товаров</h1><br>
<form class="js-good-create-form" method="POST" action="{% url 'lesson4:good_create' %}" >
    {% csrf_token %}
    <div class="modal-body">
        {% include 'form.html' %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Create good</button>
    </div>
</form>
{% endblock %}

L5/lesson4/templates/goods_list.html
{% extends 'base.html' %}
{% load static %}
{% block javascript %}
    <script src="{% static 'js/myscript.js' %}" type="text/javascript"></script>
{% endblock %}
{% block content %}
    <h1>Таблица товаров</h1><br>
    {% include 'partial_goods_list.html' %}
    <button type="submit" class="js-create-good btn btn-primary" data-url="{% url 'lesson4:good_create' %}">Добавить строку</button>

    <div class="modal fade" id="modal-good">
        <div class="modal-dialog">
            <div class="modal-content">

            </div>
        </div>
    </div>
{% endblock %}


L5/lesson4/templates/partial_goods_list.html
<table class="table table-bordered">
    <thead>
        <tr>
            <th>{{ product_name }}</th>
            <th>{{ product_date }}</th>
            <th>{{ product_price }}</th>
            <th>{{ product_u_measure }}</th>
            <th>{{ product_provider }}</th>
        </tr>
    </thead>
    <tbody id="good-table">
        {% for i in table %}
        <tr>
            <td>{{ i.name }}</td>
            <td>{{ i.date_rec }}</td>
            <td>{{ i.price }}</td>
            <td>{{ i.u_measure }}</td>
            <td>{{ i.name_provider }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

L5/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Урок 4</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="shortcut icon" href="#">
</head>
<body>
<div class="container">
       {% block content %}
       {% endblock %}
</div>

<script src="{% static 'js/jquery-3.5.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
{% block javascript %}
{% endblock %}
</body>
</html>

L5/templates/form.html
{% load bootstrap %}
{% load widget_tweaks %}
{{ form | bootstrap }}
<!--<button type="submit" class="btn btn-success">Сохранить</button>-->